version: '3.4'

services:
  edr.api:
    build:
      context: .
      dockerfile: Edr.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SimpleProperty="hello-from-compose"
    depends_on:
      - seq_in_dc

  edr.app:
    build:
      context: .
      dockerfile: Edr.App/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - seq_in_dc

  edr.podprocessor:
    build:
      context: .
      dockerfile: Edr.PodProcessor/Dockerfile
    depends_on:
      - seq_in_dc
      

  seq_in_dc:
    image: datalust/seq
    ports:
      - "8005:80"
    environment:
      - ACCEPT_EULA=Y

  sql_in_dc:
    build:
      context: .
      dockerfile: sql/sql.Dockerfile
    restart: always
    ports:
      - "1440:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1!
